spring.application.name=ToDo-microservice

server.port=8090

# Import .env file
spring.config.import=optional:file:.env[.properties]

### PostGreSQL ###
spring.datasource.url=${CONNECTION_STRING_POSTGRESQL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}

### Flyway ###
# --- Flyway (JDBC driver), doesn't know about R2DBC ahead of time
spring.flyway.url=${SPRING_FLYWAY_URL}
spring.flyway.user=${SPRING_FLYWAY_USER}
spring.flyway.password=${SPRING_FLYWAY_PASSWORD}

# Flyway directory path to db.migration
spring.flyway.locations=classpath:db/migration

# Required if table is being put in already existing db (first time app runs)
# Best practice: keep set to true even after first time running app
spring.flyway.baseline-on-migrate=true

### RateLimiter ###
resilience4j.ratelimiter.instances.myRateLimiter.limitForPeriod=100
resilience4j.ratelimiter.instances.myRateLimiter.limitRefreshPeriod=60s
resilience4j.ratelimiter.instances.myRateLimiter.timeoutDuration=1s
